apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: valheim-k8s
  releaseName: valheim-server
  version: 1.1.0
  repo: https://addyvan.github.io/valheim-k8s/
  valuesFile: values.yaml
  namespace: valheim
  # valuesInline:
  #   containerPort:
  #     http: 81

# resources:
# - 

# patches:
# - 