apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- loadbalancer.yaml
# - storageclass.yaml
# - path: storagename.json
# target:
#     kind: Deployment
#     name: vrising
#   patch: 
#     - op: replace
#       path: "/spec/template/spec/volumes/vrising-claim0/persistentVolumeClaim"
#       value: vrising

# Manually create configmaps
# configMapGenerator:
# - name: vrising-ServerHostSettings
#   files:
#   - ServerHostSettings.json
# - name: vrising-ServerGameSettings
#   files:
#   - ServerGameSettings.json