apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- storageclass.yaml
- loadbalancer.yaml

# Manually create configmaps
# configMapGenerator:
# - name: vrising-ServerHostSettings
#   files:
#   - ServerHostSettings.json
# - name: vrising-ServerGameSettings
#   files:
#   - ServerGameSettings.json