apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: longhorn
  releaseName: longhorn
  version: 1.5.1
  repo: https://charts.longhorn.io
  # valuesFile: values.yaml
  namespace: longhorn-system
  # valuesInline:
  #   containerPort:
  #     http: 81

# resources:
# - 

# patches:
# - 
