# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: config
data:
  config: |
    ipAddressPools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.1.20-192.168.1.40