# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: config
data:
  config: |
    ipAddressPools:
    - name: default
      protocol: layer2
      addresses:
      - 10.0.0.80-10.0.0.99