apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-upgrade-controller
  namespace: system-upgrade
spec:
  toleration:
  - key: "k3s-controlplane"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"