apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: audiobookshelf
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: user/manifests/audiobookshelf/elite-cluster
    repoURL: https://github.com/todaywasawesome/elite-cluster.git
    targetRevision: HEAD
  sources: []
  project: elite-cluster
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
    syncOptions:
      - ServerSideApply=true