# app-1password-connect.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd 
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/todaywasawesome/elite-cluster
    targetRevision: HEAD
    path: user/manifests/external-secrets/elite-cluster
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true