apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp-in-cluster-headlamp2
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: deploystudio
    deploystudio/app: headlamp
    deploystudio/version: 0.45.0
  annotations:
    deploystudio/app-id: ""
spec:
  project: default
  source:
    repoURL: https://github.com/todaywasawesome/elite-cluster
    targetRevision: main
    path: clusters/homelab/headlamp
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp2
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
