apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-gpu-plugin
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: intel-gpu-plugin
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://intel.github.io/helm-charts'
    targetRevision: 0.27.0
    chart: intel-device-plugins-gpu
  sources: []
  project: elite-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
