apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: longhorn-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.longhorn.io'
    targetRevision: 1.4.3
    chart: longhorn
  sources: []
  project: elite-cluster
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
