apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: longhorn-system
    server: 'https://kubernetes.default.svc'
  source:
    path: user/manifests/longhorn/elite-cluster
    repoURL: 'https://github.com/todaywasawesome/elite-cluster'
    targetRevision: HEAD
  project: elite-cluster
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
