apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: metallb-system
    server: 'https://kubernetes.default.svc'
  source:
    path: user/manifests/metallb/elite-cluster
    repoURL: 'https://github.com/todaywasawesome/elite-cluster'
    targetRevision: HEAD
  project: elite-cluster
  ignoreDifferences:
  - group: "apiextensions.k8s.io"
    kind: CustomResourceDefinition
    name: bgppeers.metallb.io
    jsonPointers:
    - /spec/conversion/webhook/clientConfig/caBundle
  - group: "apiextensions.k8s.io"
    kind: CustomResourceDefinition
    name: addresspools.metallb.io
    jsonPointers:
    - /spec/conversion/webhook/clientConfig/caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
