# app-1password-connect.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openclaw
  namespace: argocd 
spec:
  destination:
    namespace: openclaw
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/todaywasawesome/elite-cluster'
    targetRevision: HEAD
    path: user/manifests/openclaw/elite-cluster
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true