apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  codefresh.io/product: plex
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: plex-system
    server: 'https://kubernetes.default.svc'
  source:
    path: user/manifests/plex/elite-cluster
    repoURL: 'https://github.com/todaywasawesome/elite-cluster'
    targetRevision: HEAD
    plugin: 
      name: kustomize-build-with-helm
  project: elite-cluster
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #     - CreateNamespace=true
  #     - ServerSideApply=true
