apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  annotations:
    argo.octopus.com/project: "sonarr"
    argo.octopus.com/environment: "elite-cluster"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: user/manifests/sonarr/elite-cluster
    repoURL: 'https://github.com/todaywasawesome/elite-cluster'
    targetRevision: HEAD
    plugin: 
      name: kustomize-build-with-helm
  project: elite-cluster
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
