apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: speedtest-tracker
  codefresh.io/product: speedtest-tracker
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: speedtest-tracker
    server: 'https://kubernetes.default.svc'
  source:
    path: user/manifests/speedtest-tracker/elite-cluster
    repoURL: 'https://github.com/todaywasawesome/elite-cluster'
    targetRevision: HEAD

  project: elite-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
