apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: upgrade-controller
spec:
  destination:
    name: ''
    namespace: system-upgrade
    server: 'https://kubernetes.default.svc'
  source:
    path: ./manifests/system-upgrade-controller.yaml
    repoURL: 'https://github.com/rancher/system-upgrade-controller/'
    targetRevision: v0.13.2
  sources: []
  project: elite-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
