kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "moonin"
  namespace: "moonin"
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "15"
  numberOfInstances: 2
  enableMasterLoadBalancer: true
  volume:
    size: "5Gi"
    storageClass: "longhorn"


  allowedSourceRanges:
    # IP ranges to access your cluster go here
  
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi