apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: moonin
resources:
- db.yaml
- api_server-service-deployment.yaml
- background-deployment.yaml
# - https://github.com/danswer-ai/danswer//deployment/kubernetes/env-configmap.yaml # Moved to config map generator
# - https://github.com/danswer-ai/danswer//deployment/kubernetes/nginx-configmap.yaml # Moved to config map generator
- nginx-service-deployment.yaml
- persistent-volumes.yaml
# - https://github.com/danswer-ai/danswer//deployment/kubernetes/postgres-service-deployment.yaml # Using separate postgres database
# - secrets.yaml #Not needed
- vespa-service-deployment.yaml
- web_server-service-deployment.yaml

configMapGenerator:
- name: env-configmap
  literals:
    # Auth Setting, also check the secrets file
    - AUTH_TYPE="disabled"  # Change this for production uses unless Danswer is only accessible behind VPN
    - SESSION_EXPIRE_TIME_SECONDS="86400"  # 1 Day Default
    - VALID_EMAIL_DOMAINS=""  # Can be something like danswer.ai, as an extra double-check
    - SMTP_SERVER="" # For sending verification emails, if unspecified then defaults to 'smtp.gmail.com'
    - SMTP_PORT="" # For sending verification emails, if unspecified then defaults to '587'
    - SMTP_USER=""  # 'your-email@company.com'
    - SMTP_PASS=""  # 'your-gmail-password'
    # Gen AI Settings
    - GEN_AI_MODEL_PROVIDER="VLLM"
    - GEN_AI_MODEL_VERSION="TheBloke/Mistral-7B-Instruct-v0.2-GPTQ"  # Use GPT-4 if you have it
    - FAST_GEN_AI_MODEL_VERSION="TheBloke/Mistral-7B-Instruct-v0.2-GPTQ"
    - GEN_AI_API_KEY="EMPTY"
    - GEN_AI_API_ENDPOINT="http://10.0.0.51:8000/"
    - GEN_AI_API_VERSION="v1"
    - GEN_AI_LLM_PROVIDER_TYPE="VLLM"
    - QA_TIMEOUT="60"
    - NUM_DOCUMENT_TOKENS_FED_TO_GENERATIVE_MODEL=""
    - DISABLE_LLM_FILTER_EXTRACTION=""
    - DISABLE_LLM_CHUNK_FILTER=""
    - DISABLE_LLM_CHOOSE_SEARCH=""
    # Query Options
    - DOC_TIME_DECAY=""
    - HYBRID_ALPHA=""
    - EDIT_KEYWORD_QUERY=""
    - MULTILINGUAL_QUERY_EXPANSION=""
    - QA_PROMPT_OVERRIDE=""
    # Other Services
    - POSTGRES_HOST="moonin"
    - VESPA_HOST="document-index-service"
    # Don't change the NLP models unless you know what you're doing
    - DOCUMENT_ENCODER_MODEL=""
    - NORMALIZE_EMBEDDINGS=""
    - ASYM_QUERY_PREFIX=""
    - ASYM_PASSAGE_PREFIX=""
    - ENABLE_RERANKING_REAL_TIME_FLOW=""
    - ENABLE_RERANKING_ASYNC_FLOW=""
    - MODEL_SERVER_HOST="10.0.0.51"
    - MODEL_SERVER_PORT="8000"
    - INDEXING_MODEL_SERVER_HOST=""
    - MIN_THREADS_ML_MODELS=""
    # Indexing Configs
    - NUM_INDEXING_WORKERS=""
    - DASK_JOB_CLIENT_ENABLED=0
    - CONTINUE_ON_CONNECTOR_FAILURE=""
    - EXPERIMENTAL_CHECKPOINTING_ENABLED=""
    - CONFLUENCE_CONNECTOR_LABELS_TO_SKIP=""
    - GONG_CONNECTOR_START_TIME=""
    - NOTION_CONNECTOR_ENABLE_RECURSIVE_PAGE_LOOKUP=""
    # DanswerBot SlackBot Configs
    # - DANSWER_BOT_SLACK_APP_TOKEN="" #Set in app
    # - DANSWER_BOT_SLACK_BOT_TOKEN=""
    - DANSWER_BOT_DISABLE_DOCS_ONLY_ANSWER=""
    - DANSWER_BOT_DISPLAY_ERROR_MSGS=""
    - DANSWER_BOT_RESPOND_EVERY_CHANNEL=""
    - DANSWER_BOT_DISABLE_COT=""  # Currently unused
    - NOTIFY_SLACKBOT_NO_ANSWER=""
    # Logging
    # Optional Telemetry, please keep it on (nothing sensitive is collected)? <3
    # https://docs.danswer.dev/more/telemetry
    - DISABLE_TELEMETRY=""
    - LOG_LEVEL=""
    - LOG_ALL_MODEL_INTERACTIONS=""
    - LOG_VESPA_TIMING_INFORMATION=""
    # Shared or Non-backend Related
    - INTERNAL_URL="http://api-server-service:80"  # for web server
    - WEB_DOMAIN="http://localhost:3000"  # for web server and api server
    - DOMAIN="localhost"  # for nginx
- name: nginx-configmap
  files:
  - nginx.conf


patches:
- target: #Replace resources
    kind: Deployment
    name: background-deployment
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: background-deployment
      annotations:
        argocd.argoproj.io/sync-options: Replace=true
- target: #Replace Resources
    kind: Deployment
    name: api-server-deployment
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: api-server-deployment
      annotations:
        argocd.argoproj.io/sync-options: Replace=true