apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: speedtest-tracker
    spec:
      template:
        spec:
          dnsPolicy: ClusterFirst
          dnsConfig: 
            nameservers:
              - 1.1.1.1
              - 8.8.8.8
            searches:
              - speedtest-tracker.svc.cluster.local
            options:
              - name: ndots
                value: "5"

