apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- sonarr.yaml

# patches:
# - 

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: sonarr-deployment
  spec:
    template:
      spec:
        containers:
        - name: sonarr
          image: linuxserver/sonarr:3.0.9