---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: sonarr-deployment
   labels:
     app: sonarr
 spec:
   replicas: 1
   selector:
      matchLabels:
        app: sonarr
   template:
     metadata:
       labels:
         app: sonarr
 
     spec:
      containers:
         - name: sonarr
           image: linuxserver/sonarr
           imagePullPolicy: Always
           ports:
             - containerPort: 8989
           resources:
             requests:
               cpu: "1000m"
               memory: "512Mi"
           volumeMounts:
             - mountPath: /config
               name: sonarr-config
             - mountPath: /tv
               name: sonarr-tv
      volumes:
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr
        - name: sonarr-tv
          persistentVolumeClaim:
            claimName: media
---
kind: Service
apiVersion: v1
metadata:
  name: sonarr-service
spec:
  selector:
    app: sonarr
  ports:
  - protocol: TCP
    port: 8989
    targetPort: 8989
  type: NodePort