apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres-operator
resources:
- https://github.com/zalando/postgres-operator//manifests/?ref=v1.11.0 #Deploy base
- https://github.com/zalando/postgres-operator//ui/manifests/?ref=v1.11.0 #Deploy UI
- dynamic-permissions.yaml

configMapGenerator:
- name: postgres-operator
  behavior: merge
  literals:
  - OPERATOR_API_URL=postgres-opreator.postgres-operator.svc.cluster.local:8080

patches:
- target: #Deploy operator deployment last
    kind: Deployment
    name: postgres-operator
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: postgres-operator
      annotations:
        argocd.argoproj.io/sync-wave: "5"
- target: #Remove Ingress
    kind: Ingress
    name: postgres-operator-ui
  patch: |-
    $patch: delete
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: postgres-operator-ui
- target: #Set Service to use loadbalancer ip
    kind: Service
    name: postgres-operator-ui
  patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: postgres-operator-ui
    spec:
      type: LoadBalancer
- target: #Have UI watch all namespaces
    kind: Deployment
    name: postgres-operator-ui
  patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/1"
      value:
        name: targetNamespace
        value: "*"
- target: #Have UI watch all namespaces
    kind: Deployment
    name: postgres-operator-ui
  patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/1"
      value:
        name: TARGET_NAMESPACE
        value: "*"
- target: #Have UI watch all namespaces
    kind: Deployment
    name: postgres-operator-ui
  patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/1"
      value:
        name: watched_namespace
        value: "*"
# - target: #Give UI permissions
#     kind: ClusterRole
#     name: postgres-operator-ui
#   patch: |-
#     - op: merge
#       path: "/rules/0"
#       value:
#         apiGroups:
#           - 