apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/zalando/postgres-operator//manifests/?ref=v1.10.1 #Deploy base
- https://github.com/zalando/postgres-operator//ui/manifests/?ref=v1.10.1 #Deploy UI