apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- radarr.yaml

# patches:
# - 

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: radarr-deployment
  spec:
    template:
      spec:
        containers:
        - name: radarr
          image: linuxserver/radarr:5.16.3
