---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: radarr-deployment
   labels:
     app: radarr
 spec:
   replicas: 1
   selector:
      matchLabels:
        app: radarr
   strategy:
    type: Recreate
   template:
     metadata:
       labels:
         app: radarr
 
     spec:
      containers:
         - name: radarr
           image: linuxserver/radarr
           imagePullPolicy: Always
           ports:
             - containerPort: 7878
           env:
            - name: PUID
              value: "1002"
            - name: PGID
              value: "1002"
           resources:
             requests:
               cpu: "1000m"
               memory: "512Mi"
           volumeMounts:
             - mountPath: /config
               name: radarr-config
             - mountPath: /downloads
               name: radarr-downloads
             - mountPath: /movies
               name: radarr-movies
      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr
        - name: radarr-downloads
          persistentVolumeClaim:
            claimName: download
        - name: radarr-movies
          persistentVolumeClaim:
            claimName: media
---
kind: Service
apiVersion: v1
metadata:
  name: radarr-service
spec:
  selector:
    app: radarr
  ports:
  - protocol: TCP
    port: 7878
    targetPort: 7878
  type: LoadBalancer